services:
    leads-core-php-cli:
        build:
            context: ./.docker/development
            dockerfile: php/Dockerfile
        container_name: leads-core-php-cli
        volumes:
            - "$PWD/app:/var/www/app:rw"
            - "$PWD/.data/composer:/root/.composer/cache"
        environment:
            PHP_IDE_CONFIG: "serverName=leads-core"
            XDEBUG_CONFIG: "remote_host=192.168.221.1 remote_enable=1"
        networks:
            - plat-leads-network

networks:
    plat-leads-network:
        name: plat-leads-network
        driver: bridge
        driver_opts:
            com.docker.network.driver.mtu: 1440
        ipam:
            driver: default
            config:
                -   subnet: 192.168.221.0/24
