services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Leads\Core\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Pagination/'
            - '../../Exception/'
